### ISSUE TITLE
Not loading the mermaid javascript file properly

### ISSUE THREAD

**Issue by mtrienis** [jasonbellamy/jekyll-mermaid#1]
I am not seeing the rendered flow diagram from the example you provided in the readme.md. It seems to be a loading sequence issue because if I execute

`mermaid.init(undefined, $(".mermaid"));` 

The diagrams start to render although the styles seem to be messed up.

**Comment by jasonbellamy** [comment]
This seems to be an issue with the initialization for newer versions of mermaid. I'm looking in to it via https://github.com/jasonbellamy/jekyll-mermaid/issues/5
