### ISSUE TITLE
tag `mermaid` makes building fail

### ISSUE THREAD

**Issue by ghost** [jasonbellamy/jekyll-mermaid#2]
Hi,

I just received an email notifying me that:

> The page build failed with the following error:
> 
> The tag `mermaid` in `_posts/...` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.
> 
> If you have any questions you can contact us by replying to this email.

But it works fine locally.

Here is [my config](https://github.com/haodong/haodong.github.io/blob/master/_config.yml) and [the failed page](https://github.com/haodong/haodong.github.io/blob/master/_posts/2016-01-18-use-aria2-with-client-certificate-authentication.md).

Thanks.

**Comment by flpydisk** [comment]
the Jekyll generator on GitHub has specific supported old version with specific plugins. You cannot add more than the list they have. Unfortunately, mermaid gem is not supported yet.
