### ISSUE TITLE
where can I get the exact mermaid.js

### ISSUE THREAD

**Issue by flpydisk** [jasonbellamy/jekyll-mermaid#4]
Hi

I searched in the mermaid official respo. and I found 4 files that are named mermaid.js

![search list](https://sites.google.com/site/tempbomkarram/img/2016-01-27%2022_53_02-mermaid.js%20-%20Search%20Results%20in%20mermaid-master.png)

which one should I pick?

**Comment by jasonbellamy** [comment]
Please checkout the documentation from the mermaid website, and choose which one suits you best: https://knsv.github.io/mermaid/#installation
